-- MySQL Script generated by MySQL Workbench
-- 04/12/17 12:10:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(45) NOT NULL,
  `profile` ENUM('CLIENT', 'EMPLOYEE', 'MANAGER', 'OWNER') NOT NULL,
  `state` ENUM('ACTIVE', 'INACTIVE') NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`businesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`businesses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`businesses` (
  `business_id` INT NOT NULL,
  `business_name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`business_id`),
  UNIQUE INDEX `business_name_UNIQUE` (`business_name` ASC),
  INDEX `fk_businesses_users1_idx` (`user_id` ASC),
  INDEX `fk_businesses_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_businesses_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_businesses_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subcategories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subcategories` (
  `subcategory_id` INT NOT NULL,
  `subcategory_name` VARCHAR(45) NOT NULL,
  `subcategory_description` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`subcategory_id`),
  UNIQUE INDEX `subcategory_name_UNIQUE` (`subcategory_name` ASC),
  INDEX `fk_Subcategories_Categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_Subcategories_Categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`addresses` (
  `address_id` INT NOT NULL,
  `street_nbr` VARCHAR(45) NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `floor_number` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `latitud` VARCHAR(45) NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`branches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`branches` (
  `branch_id` INT NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `business_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `fk_branches_businesses1_idx` (`business_id` ASC),
  INDEX `fk_branches_addresses1_idx` (`address_id` ASC),
  CONSTRAINT `fk_branches_businesses1`
    FOREIGN KEY (`business_id`)
    REFERENCES `mydb`.`businesses` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branches_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`addresses` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`services` ;

CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `service_id` INT NOT NULL,
  `service_name` VARCHAR(45) NOT NULL,
  `service_duration` INT(2) NOT NULL,
  `state` ENUM('ACTIVE', 'INACTIVE') NOT NULL,
  `branch_id` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_services_branches1_idx` (`branch_id` ASC),
  INDEX `fk_services_subcategories1_idx` (`subcategory_id` ASC),
  CONSTRAINT `fk_services_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_services_subcategories1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mydb`.`subcategories` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schedules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schedules` (
  `schedule_id` INT NOT NULL,
  `sunday` VARCHAR(45) NOT NULL,
  `monday` VARCHAR(45) NOT NULL,
  `tuesday` VARCHAR(45) NOT NULL,
  `wednesday` VARCHAR(45) NOT NULL,
  `thursday` VARCHAR(45) NOT NULL,
  `friday` VARCHAR(45) NOT NULL,
  `service_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedules_services1_idx` (`service_id` ASC),
  INDEX `fk_schedules_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_schedules_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedules_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`appointments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`appointments` (
  `appointment_id` INT NOT NULL,
  `appointment` VARCHAR(45) NOT NULL,
  `appointment_state` ENUM('PENDING', 'CONFIRMED', 'CANCELLED') NOT NULL,
  `user_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `fk_appointments_users1_idx` (`user_id` ASC),
  INDEX `fk_appointments_users2_idx` (`employee_id` ASC),
  CONSTRAINT `fk_appointments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_users2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
