INSERT INTO users (first_name, last_name ,telephone , email, password, dob, profile , state) VALUES
('Agustin', 'Larrarte', '1586598654', 'alarrarte@mail.com', '1234abcd', '19821112', 'CLIENT', 'ACTIVE'),
('Luciano', 'Charlier', '1586598654', 'lcharlier@mail.com', '1234abcd', '0', 'CLIENT', 'INACTIVE'),
('Luciano', 'Natoli', '1586598654', 'lnatoli@mail.com', '1234abcd', '19790102', 'CLIENT', 'ACTIVE'),
('Maotse', 'Hernandez', '1586598654', 'mhernandez@mail.com', '1234abcd', '0', 'MANAGER', 'ACTIVE');

INSERT INTO categories (category_name,description) VALUES
('Automotive Auto Accessories', 'AAAADESCRIPCIONBB'),
('Business Support & Supplies Consultants', 'AAAADESCRIPCIONBB'),
('Computers & Electronics', 'AAAADESCRIPCIONBB'),
('Construction & Contractors', 'AAAADESCRIPCIONBB'),
('Education', 'AAAADESCRIPCIONBB'),
('Entertainment', 'AAAADESCRIPCIONBB'),
('Food & Dining', 'AAAADESCRIPCIONBB'),
('Health & Medicine', 'AAAADESCRIPCIONBB'),
('Home & Garden', 'AAAADESCRIPCIONBB'),
('Legal & Financial', 'AAAADESCRIPCIONBB'),
('Manufacturing, Wholesale, Distribution', 'AAAADESCRIPCIONBB'),
('Merchants (Retail)', 'AAAADESCRIPCIONBB'),
('Miscellaneous', 'AAAADESCRIPCIONBB'),
('Personal Care & Services', 'AAAADESCRIPCIONBB'),
('Real Estate', 'AAAADESCRIPCIONBB'),
('Travel & Transportation', 'AAAADESCRIPCIONBB');

INSERT INTO subcategories (subcategory_name,subcategory_description,category_id) VALUES
('Auto Dealers – New','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Auto Dealers – Used','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Detail & Carwash','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Gas Stations','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Motorcycle Sales & Repair','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Rental & Leasing','ABBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Service, Repair & Parts','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Towing','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Automotive Auto Accessories')),
('Employment Agency','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Business Support & Supplies Consultants')),
('Marketing & Communications','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Business Support & Supplies Consultants')),
('Office Supplies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Business Support & Supplies Consultants')),
('Printing & Publishing','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Business Support & Supplies Consultants')),
('Computer Programming & Support','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Computers & Electronics')),
('Consumer Electronics & Accessories','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Computers & Electronics')),
('Architects, Landscape Architects, Engineers & Surveyors','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Blasting & Demolition','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Building Materials & Supplies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Construction Companies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Electricians','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Engineer, Survey','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Environmental Assessments','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Inspectors','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Plaster & Concrete','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Plumbers','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Roofers','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Construction & Contractors')),
('Adult & Continuing Education','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Education')),
('Early Childhood Education','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Education')),
('Educational Resources','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Education')),
('Other Educational','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Education')),
('Artists, Writers','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Entertainment')),
('Event Planners & Supplies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Entertainment')),
('Golf Courses','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Entertainment')),
('Movies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Entertainment')),
('Productions','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Entertainment')),
('Desserts, Catering & Supplies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Food & Dining')),
('Fast Food & Carry Out','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Food & Dining')),
('Grocery, Beverage & Tobacco','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Food & Dining')),
('Restaurants','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Food & Dining')),
('Acupuncture','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Assisted Living & Home Health Care','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Audiologist','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Chiropractic','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Clinics & Medical Centers','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Dental','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Diet I& Nutrition','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Laboratory, Imaging & Diagnostic','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Massage Therapy','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Mental Health','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Nurse','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Optical','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Pharmacy, Drug & Vitamin Stores','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Physical Therapy','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Physicians & Assistants','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Podiatry','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Social Worker','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Animal Hospital','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Veterinary & Animal Surgeons','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Health & Medicine')),
('Antiques & Collectibles','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Cleaning','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Crafts, Hobbies & Sports','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Flower Shops','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Home Furnishings','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Home Goods','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Home Improvements & Repairs','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Landscape & Lawn Service','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Pest Control','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Pool Supplies & Service','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Security System & Services','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Home & Garden')),
('Accountants','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Legal & Financial')),
('Attorneys','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Legal & Financial')),
('Financial Institutions','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Legal & Financial')),
('Financial Services','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Legal & Financial')),
('Insurance','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Legal & Financial')),
('Other Legal','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Legal & Financial')),
('Distribution, Import/Export','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Manufacturing, Wholesale, Distribution')),
('Manufacturing','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Manufacturing, Wholesale, Distribution')),
('Wholesale','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Manufacturing, Wholesale, Distribution')),
('Cards & Gifts','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Merchants (Retail)')),
('Clothing & Accessories','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Merchants (Retail)')),
('Department Stores, Sporting Goods','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Merchants (Retail)')),
('General','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Merchants (Retail)')),
('Jewelry','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Merchants (Retail)')),
('Shoes','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Merchants (Retail)')),
('Civic Groups','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Miscellaneous')),
('Funeral Service Providers & Cemetaries','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Miscellaneous')),
('Miscellaneous','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Miscellaneous')),
('Utility Companies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Miscellaneous')),
('Animal Care & Supplies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Barber & Beauty Salons','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Beauty Supplies','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Dry Cleaners & Laundromats','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Exercise & Fitness','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Massage & Body Works','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Nail Salons','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Shoe Repairs','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Tailors','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Personal Care & Services')),
('Agencies & Brokerage','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Real Estate')),
('Agents & Brokers','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Real Estate')),
('Apartment & Home Rental','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Real Estate')),
('Mortgage Broker & Lender','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Real Estate')),
('Property Management','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Real Estate')),
('Title Company','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Real Estate')),
('Hotel, Motel & Extended Stay','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Travel & Transportation')),
('Moving & Storage','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Travel & Transportation')),
('Packaging & Shipping','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Travel & Transportation')),
('Transportation','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Travel & Transportation')),
('Travel & Tourism','BBBBDESCIPTIONXXXX', (SELECT category_id FROM categories WHERE category_name = 'Travel & Transportation')),